image: tmaier/docker-compose:latest

services:
  - docker:dind

build:
  stage: test
  before_script:
    - cp /env/docker.env runner/.env
    - cp /env/runner.env runner/.data/
  script: docker-compose -f runner/docker-compose.yml up --build --abort-on-container-exit
  after_script:
    - docker-compose -f runner/docker-compose.yml down -v
  only:
    refs:
      - merge_requests
