### 服务端口号
server:
  port: 8080

### log4j2配置 ###
logging:
  config: classpath:log4j2.xml

spring:
  cloud:
    ### 注册中心地址
    nacos:
      discovery:
        server-addr: ${NACOS_DISCOVERY_SERVER_ADDR}
    ### sentinel dashboard
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD_URI}
      # 取消Sentinel控制台懒加载
      eager: true

  ### 为true设置的是web开启sleuth功能
  sleuth:
    web:
      client:
        enabled: true
    # 可以设置为小数，最大值为1.0，当设置为1.0时就是链路数据100%收集到zipkin-server，当设置为0.1时，即10%概率收集链路数据
    sampler:
      probability: 1.0

  ### 指定了 Zipkin 服务器的地址
  zipkin:
    base-url: ${ZIPKIN_BASE_URI}

  servlet:
    multipart:
      # 上传限制：100MB
      max-file-size: 100MB
      max-request-size: 100MB

### feign 配置
feign:
  # 打开 Sentinel 对 Feign 的支持
  sentinel:
    enabled: true
  # 超时时间（毫秒）
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

# 上传相关
upload:
  # 保存到服务器地址
  savePath: /myopia/uploadPic
  # 可上传的文件类型后缀
  suffixs: pdf,jpg,jpeg,png,xlsx
  # 上传S3的bucket
  bucketName: ${AWS_S3_BUCKET}
  # 文件上传S3的prefix
  prefix: ${AWS_S3_PREFIX}/upload
  # 静态文件上传S3的prefix，该目录文件的访问链接要求不能过期
  staticPrefix: ${AWS_S3_PREFIX}/public
  # s3的类型，取值：aws、minio
  s3-type: aws
  # 地址，s3-type为minio时必填
  endpoint: ${AWS_S3_ENDPOINT}
  # S3链接失效时间（小时）
  expiredHours: 2
  # 地区
  region: ${AWS_REGION}


### 健康监控 - actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
