### 服务端口号
server:
  port: 8050

### log4j2配置 ###
logging:
  config: classpath:log4j2.xml

### 配置Mybatis-plus的xml路径，多个用逗号隔开 ###
mybatis-plus:
  mapper-locations: classpath*:/mapping/*.xml

spring:
  cloud:
    ### 注册中心地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    ### sentinel dashboard
    sentinel:
      transport:
        dashboard: localhost:8080
      # 取消Sentinel控制台懒加载
      eager: true

  ### 为true设置的是web开启sleuth功能
  sleuth:
    web:
      client:
        enabled: true
    # 可以设置为小数，最大值为1.0，当设置为1.0时就是链路数据100%收集到zipkin-server，当设置为0.1时，即10%概率收集链路数据
    sampler:
      probability: 1.0

  ### 指定了 Zipkin 服务器的地址
  zipkin:
    base-url: http://127.0.0.1:9411

  datasource:
    druid:
      ### 数据库配置
      url: jdbc:mysql://localhost:3306/myopia?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234567890
      ### 连接池配置
      initial-size: 2
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      ### SQL监控统计配置
      filters: stat,wall
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: false
      ### 在线监控面板账号密码
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: admin
        login-password: 123456
        allow:

  ### Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    redisson:
      file: classpath:redisson.yaml

  servlet:
    multipart:
      # 上传限制：100MB
      max-file-size: 100MB
      max-request-size: 100MB

  jackson:
    serialization:
      write-dates-as-timestamps: true
    time-zone: Asia/Shanghai

### feign 配置
feign:
  # 打开 Sentinel 对 Feign 的支持
  sentinel:
    enabled: true
  # 超时时间（毫秒）
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

vistel:
  tools:
    remoteAddress: http://tools.internal

file:
  temp:
    save-path: /app/file/

### 健康监控 - actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always